config: /users/p22034/fouilhe/in-context-learning/src/conf/polynomial_regression.yaml
inherit:
- /users/p22034/fouilhe/in-context-learning/src/conf/base.yaml
- /users/p22034/fouilhe/in-context-learning/src/conf/models/tiny.yaml
model:
  family: gpt2
  n_dims: 20
  n_embd: 64
  n_head: 2
  n_layer: 3
  n_positions: 256
out_dir: models/polynomial_regression/polynomial_regression_tiny_1D_nonprogressive_deg4de9d97ac-a825-4e58-8682-785050cf5366
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 11
    polynomial_degree:
      end: 4
      inc: 1
      interval: 10000
      start: 4
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: polynomial_regression
  task_kwargs: {}
  train_steps: 500001
wandb:
  entity: ''
  log_every_steps: 100
  name: polynomial_regression_tiny_1D_nonprogressive_deg4
  notes: ''
  project: in-context-training
