config: /users/p22034/fouilhe/in-context-learning/src/conf/polynomial_regression.yaml
inherit:
- /users/p22034/fouilhe/in-context-learning/src/conf/base.yaml
- /users/p22034/fouilhe/in-context-learning/src/conf/models/4layers.yaml
model:
  family: gpt2
  n_dims: 1
  n_embd: 64
  n_head: 2
  n_layer: 4
  n_positions: 256
out_dir: models/polynomial_regression/1d_4layers_deg_4_06-24_15-29
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 11
    polynomial_degree:
      end: 4
      inc: 1
      interval: 5000
      start: 1
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: polynomial_regression
  task_kwargs: {}
  train_steps: 500001
wandb:
  entity: ''
  log_every_steps: 100
  name: 1d_4layers_deg_4
  notes: ''
  project: in-context-training
