config: /users/p22034/fouilhe/in-context-learning/src/conf/linear_regression.yaml
inherit:
- /users/p22034/fouilhe/in-context-learning/src/conf/base.yaml
- /users/p22034/fouilhe/in-context-learning/src/conf/models/tiny.yaml
model:
  family: gpt2
  n_dims: 20
  n_embd: 64
  n_head: 2
  n_layer: 3
  n_positions: 101
out_dir: models/linear_regression/b821472e-0b5d-43ce-8828-15216c50f6f3
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 2000
      start: 5
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: linear_regression
  task_kwargs: {}
  train_steps: 500001
wandb:
  entity: in-context
  log_every_steps: 100
  name: linear_regression_standard
  notes: ''
  project: in-context-training
